language: clojure
lein: 2.9.1
dist: bionic

services:
  - docker

script:
  - ./ext/travisci/test.sh
  - $TRAVIS_BUILD_DIR/ext/travisci/secscan.sh "$TRAVIS_BUILD_DIR/src/clj" "clj"
jobs:
  include:
    - stage: puppetserver tests
      name: "Java 8"
      jdk: openjdk8
    - jdk: openjdk11
      name: "Java 11"
    - jdk: openjdk11
      env: ADDITIONAL_LEIN_ARGS="with-profile fips"
      name: "Java 11 w/ FIPS"
    - jdk: openjdk11
      env: MULTITHREADED=true
      name: "Java 11 w/ multithreaded"

notifications:
  email: false
